"""initial complete migration

Revision ID: 34303c9ec40b
Revises: 
Create Date: 2025-08-05 11:40:35.631316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34303c9ec40b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_rights_0', sa.Boolean(), nullable=True),
    sa.Column('user_rights_1', sa.Boolean(), nullable=True),
    sa.Column('user_rights_2', sa.Boolean(), nullable=True),
    sa.Column('user_rights_3', sa.Boolean(), nullable=True),
    sa.Column('user_rights_4', sa.Boolean(), nullable=True),
    sa.Column('user_rights_5', sa.Boolean(), nullable=True),
    sa.Column('user_rights_6', sa.Boolean(), nullable=True),
    sa.Column('user_rights_7', sa.Boolean(), nullable=True),
    sa.Column('user_rights_8', sa.Boolean(), nullable=True),
    sa.Column('user_rights_9', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_states_id'), 'states', ['id'], unique=False)
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_index(op.f('ix_statuses_id'), 'statuses', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_code'), 'subscriptions', ['code'], unique=True)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('timezones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_timezones_id'), 'timezones', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('subscription_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['subscription_code'], ['subscriptions.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advcode', sa.String(length=10), nullable=True),
    sa.Column('adv_country_id', sa.Integer(), nullable=False),
    sa.Column('adv_status_id', sa.Integer(), nullable=False),
    sa.Column('adv_state_id', sa.Integer(), nullable=False),
    sa.Column('adv_timezone_id', sa.Integer(), nullable=False),
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=127), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=127), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('active_state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['adv_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['adv_state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['adv_status_id'], ['statuses.id'], ),
    sa.ForeignKeyConstraint(['adv_timezone_id'], ['timezones.id'], ),
    sa.ForeignKeyConstraint(['company_code'], ['companies.code'], ),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code', 'email', name='uq_company_email'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_advertisers_advcode'), 'advertisers', ['advcode'], unique=False)
    op.create_index(op.f('ix_advertisers_currency'), 'advertisers', ['currency'], unique=False)
    op.create_index(op.f('ix_advertisers_id'), 'advertisers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('company_code', sa.String(length=50), nullable=True),
    sa.Column('user_code', sa.String(length=50), nullable=True),
    sa.Column('role_code', sa.String(length=50), nullable=True),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['company_code'], ['companies.code'], ),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_code')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('sub_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=127), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('user_code', sa.String(length=50), nullable=True),
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('active_state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_code'], ['companies.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code', 'email', name='uq_company_subuser_email'),
    sa.UniqueConstraint('user_code')
    )
    op.create_index(op.f('ix_sub_users_id'), 'sub_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_users_id'), table_name='sub_users')
    op.drop_table('sub_users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_advertisers_id'), table_name='advertisers')
    op.drop_index(op.f('ix_advertisers_currency'), table_name='advertisers')
    op.drop_index(op.f('ix_advertisers_advcode'), table_name='advertisers')
    op.drop_table('advertisers')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_timezones_id'), table_name='timezones')
    op.drop_table('timezones')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_code'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_statuses_id'), table_name='statuses')
    op.drop_table('statuses')
    op.drop_index(op.f('ix_states_id'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
