"""initial migration

Revision ID: 730e8bce2ad9
Revises: 
Create Date: 2025-08-04 10:46:33.996691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '730e8bce2ad9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=127), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('user_code', sa.String(length=50), nullable=True),
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('active_state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_code'], ['companies.code'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_code'], ),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code', 'email', name='uq_company_subuser_email'),
    sa.UniqueConstraint('user_code')
    )
    op.create_index(op.f('ix_sub_users_id'), 'sub_users', ['id'], unique=False)
    op.alter_column('advertisers', 'company_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_index('contact_number', table_name='advertisers')
    op.drop_index('contact_person', table_name='advertisers')
    op.drop_index('email', table_name='advertisers')
    op.drop_index('ix_advertisers_advcode', table_name='advertisers')
    op.create_index(op.f('ix_advertisers_advcode'), 'advertisers', ['advcode'], unique=False)
    op.create_unique_constraint('uq_company_email', 'advertisers', ['company_code', 'email'])
    op.drop_constraint('advertisers_ibfk_7', 'advertisers', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('advertisers_ibfk_7', 'advertisers', 'users', ['created_by'], ['user_code'])
    op.drop_constraint('uq_company_email', 'advertisers', type_='unique')
    op.drop_index(op.f('ix_advertisers_advcode'), table_name='advertisers')
    op.create_index('ix_advertisers_advcode', 'advertisers', ['advcode'], unique=True)
    op.create_index('email', 'advertisers', ['email'], unique=True)
    op.create_index('contact_person', 'advertisers', ['contact_person'], unique=True)
    op.create_index('contact_number', 'advertisers', ['contact_number'], unique=True)
    op.alter_column('advertisers', 'company_code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_sub_users_id'), table_name='sub_users')
    op.drop_table('sub_users')
    # ### end Alembic commands ###
