"""initial migration

Revision ID: 85c24be2573a
Revises: 
Create Date: 2025-09-04 14:29:58.666871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c24be2573a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('category_slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name'),
    sa.UniqueConstraint('category_slug')
    )
    op.create_index(op.f('ix_campaign_categories_id'), 'campaign_categories', ['id'], unique=False)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_rights_0', sa.Boolean(), nullable=True),
    sa.Column('user_rights_1', sa.Boolean(), nullable=True),
    sa.Column('user_rights_2', sa.Boolean(), nullable=True),
    sa.Column('user_rights_3', sa.Boolean(), nullable=True),
    sa.Column('user_rights_4', sa.Boolean(), nullable=True),
    sa.Column('user_rights_5', sa.Boolean(), nullable=True),
    sa.Column('user_rights_6', sa.Boolean(), nullable=True),
    sa.Column('user_rights_7', sa.Boolean(), nullable=True),
    sa.Column('user_rights_8', sa.Boolean(), nullable=True),
    sa.Column('user_rights_9', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_states_id'), 'states', ['id'], unique=False)
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_index(op.f('ix_statuses_id'), 'statuses', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_code'), 'subscriptions', ['code'], unique=True)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('timezones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_timezones_id'), 'timezones', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('subscription_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['subscription_code'], ['subscriptions.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advcode', sa.String(length=25), nullable=True),
    sa.Column('adv_country_id', sa.Integer(), nullable=False),
    sa.Column('adv_status_id', sa.Integer(), nullable=False),
    sa.Column('adv_state_id', sa.Integer(), nullable=False),
    sa.Column('adv_timezone_id', sa.Integer(), nullable=False),
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=127), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('active_state', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['adv_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['adv_state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['adv_status_id'], ['statuses.id'], ),
    sa.ForeignKeyConstraint(['adv_timezone_id'], ['timezones.id'], ),
    sa.ForeignKeyConstraint(['company_code'], ['companies.code'], ),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code', 'email', name='uq_company_email_advertiser'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_advertisers_advcode'), 'advertisers', ['advcode'], unique=False)
    op.create_index(op.f('ix_advertisers_id'), 'advertisers', ['id'], unique=False)
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pubcode', sa.String(length=25), nullable=True),
    sa.Column('pub_country_id', sa.Integer(), nullable=False),
    sa.Column('pub_status_id', sa.Integer(), nullable=False),
    sa.Column('pub_state_id', sa.Integer(), nullable=False),
    sa.Column('pub_timezone_id', sa.Integer(), nullable=False),
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=127), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('active_state', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['company_code'], ['companies.code'], ),
    sa.ForeignKeyConstraint(['pub_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['pub_state_id'], ['states.id'], ),
    sa.ForeignKeyConstraint(['pub_status_id'], ['statuses.id'], ),
    sa.ForeignKeyConstraint(['pub_timezone_id'], ['timezones.id'], ),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code', 'email', name='uq_company_email_publisher'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_publishers_id'), 'publishers', ['id'], unique=False)
    op.create_index(op.f('ix_publishers_pubcode'), 'publishers', ['pubcode'], unique=False)
    op.create_table('sub_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=127), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('user_code', sa.String(length=50), nullable=True),
    sa.Column('company_code', sa.String(length=50), nullable=False),
    sa.Column('active_state', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['company_code'], ['companies.code'], ),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_code', 'email', name='uq_company_subuser_email'),
    sa.UniqueConstraint('user_code')
    )
    op.create_index(op.f('ix_sub_users_id'), 'sub_users', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('company_code', sa.String(length=50), nullable=True),
    sa.Column('user_code', sa.String(length=50), nullable=True),
    sa.Column('role_code', sa.String(length=50), nullable=True),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['company_code'], ['companies.code'], ),
    sa.ForeignKeyConstraint(['role_code'], ['roles.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_code')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.Enum('CONVERSIONS', 'SALE', 'APP', 'INSTALLS', 'LEADS', 'IMPRESSIONS', 'CLICKS', name='campaignobjectiveenum'), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'ASK_FOR_PERMISSION', name='campaignvisibilityenum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'PENDING', 'DISABLED', 'SUSPENDED', 'EXPIRED', 'DELETED', name='campaignstatusenum'), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('preview_url', sa.String(length=2048), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('devices', sa.Enum('ALL', 'DESKTOP', 'MOBILE', 'TABLET', name='deviceenum'), nullable=True),
    sa.Column('os', sa.Enum('ALL', 'ANDROID', 'IOS', 'WINDOWS_OS', 'MAC_OS', name='osenum'), nullable=True),
    sa.Column('activation_date', sa.Date(), nullable=True),
    sa.Column('unique_id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['campaign_categories.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('campaign_blocked_publishers_association',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'publisher_id')
    )
    op.create_table('campaign_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('goal_title', sa.String(length=255), nullable=False),
    sa.Column('goal_value', sa.String(length=255), nullable=True),
    sa.Column('goal_type', sa.Enum('PUBLIC', 'PRIVATE', 'PUBLISHER_SPECIFIC', name='goaltypeenum'), nullable=True),
    sa.Column('hide_payout_from_publisher', sa.Boolean(), nullable=True),
    sa.Column('goal_payout_type', sa.Enum('PERCENTAGE', 'FIXED', name='goalpayouttypeenum'), nullable=True),
    sa.Column('track_multiple_conversions', sa.Enum('YES', 'YES_WITH_TXN_ID', 'NO_DISCARD', 'NO_CANCEL', name='trackmultipleconversionsenum'), nullable=True),
    sa.Column('payout_and_revenue_coverage_country_ids', sa.Text(), nullable=True),
    sa.Column('revenue', sa.String(length=255), nullable=True),
    sa.Column('payout', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_goals_id'), 'campaign_goals', ['id'], unique=False)
    op.create_table('campaign_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('payout', sa.String(length=255), nullable=False),
    sa.Column('revenue', sa.String(length=255), nullable=False),
    sa.Column('country_ids', sa.Text(), nullable=True),
    sa.Column('device_types', sa.Enum('ALL', 'DESKTOP', 'MOBILE', 'TABLET', name='deviceenum'), nullable=True),
    sa.Column('os_types', sa.Enum('ALL', 'ANDROID', 'IOS', 'WINDOWS_OS', 'MAC_OS', name='osenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_payouts_id'), 'campaign_payouts', ['id'], unique=False)
    op.create_table('campaign_publishers_association',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'publisher_id')
    )
    op.create_table('campaign_targeting_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('targeting_variable', sa.Enum('OS', 'DEVICE', name='targetingvariableenum'), nullable=False),
    sa.Column('logic', sa.Enum('ALLOW', 'BLOCK', name='logicenum'), nullable=False),
    sa.Column('rule_block_name', sa.String(length=255), nullable=True),
    sa.Column('condition', sa.Enum('MATCHES', 'EXACT_MATCH', name='conditionenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_targeting_rules_id'), 'campaign_targeting_rules', ['id'], unique=False)
    op.create_table('payout_publishers_association',
    sa.Column('payout_id', sa.Integer(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payout_id'], ['campaign_payouts.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('payout_id', 'publisher_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payout_publishers_association')
    op.drop_index(op.f('ix_campaign_targeting_rules_id'), table_name='campaign_targeting_rules')
    op.drop_table('campaign_targeting_rules')
    op.drop_table('campaign_publishers_association')
    op.drop_index(op.f('ix_campaign_payouts_id'), table_name='campaign_payouts')
    op.drop_table('campaign_payouts')
    op.drop_index(op.f('ix_campaign_goals_id'), table_name='campaign_goals')
    op.drop_table('campaign_goals')
    op.drop_table('campaign_blocked_publishers_association')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sub_users_id'), table_name='sub_users')
    op.drop_table('sub_users')
    op.drop_index(op.f('ix_publishers_pubcode'), table_name='publishers')
    op.drop_index(op.f('ix_publishers_id'), table_name='publishers')
    op.drop_table('publishers')
    op.drop_index(op.f('ix_advertisers_id'), table_name='advertisers')
    op.drop_index(op.f('ix_advertisers_advcode'), table_name='advertisers')
    op.drop_table('advertisers')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_timezones_id'), table_name='timezones')
    op.drop_table('timezones')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_code'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_statuses_id'), table_name='statuses')
    op.drop_table('statuses')
    op.drop_index(op.f('ix_states_id'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_campaign_categories_id'), table_name='campaign_categories')
    op.drop_table('campaign_categories')
    # ### end Alembic commands ###
