"""change in the advertiser module

Revision ID: e1eb6a3d2ba9
Revises: de820c872d14
Create Date: 2025-08-20 10:12:13.447030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e1eb6a3d2ba9'
down_revision: Union[str, None] = 'de820c872d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisers', 'advcode',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisers', 'advcode',
               existing_type=sa.String(length=25),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
